id: P4EAF822A
initial_creation_type: input
source_metadata:
  title: Mokṣopāya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Advaita
  data entry: Walter Slaje
  contribution to GRETIL: Walter Slaje
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:58:38.882069'
last_modified_at: '2022-03-09T14:58:38.882083'
